### ISSUE TITLE
Reorg and rename

### ISSUE THREAD

**Issue by tianyin** [xlab-uiuc/cflow#18]
@X-czh @zjzijielu I renamed the project into `cflow` as the project is not for consistency checking anymore. 

Could we do the following:
* Make the repo public
* Merge the branch in `taint_tracking` to the master branch

I'm asking for the following two reasons:
* I hope to make a public repo so it's easier for others (e.g., future students) to see the repo and work on it;
* I'm writing a letter for @samar1tan -- given that he joined too recently, I think a good data point is to show the code he wrote; but there is no way to search code by authors in branches other than the master branch.

Please let me know if you have concerns on making the repo public. Thanks!

**Comment by X-czh** [comment]
Done.
